// Code generated by "stringer -type=MsgType -trimprefix=Msg"; DO NOT EDIT.

package trace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgSlog-0]
}

const _MsgType_name = "Slog"

var _MsgType_index = [...]uint8{0, 4}

func (i MsgType) String() string {
	if i >= MsgType(len(_MsgType_index)-1) {
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
